### ISSUE TITLE
KeyError: 'Task Metrics' ？

### ISSUE THREAD

**Issue by jiadongy** [kayousterhout/trace-analysis#4]
Parsing file /home/spark/history-spark/app-20150609163608-0002 as JSON
Stage ids: [0, 1, 2, 3]
Traceback (most recent call last):
  File "./trace-analysis/parse_logs.py", line 200, in <module>
    main(sys.argv[1:])
  File "./trace-analysis/parse_logs.py", line 192, in main
    analyzer = Analyzer(filename, opts.parse_as_single_job)
  File "./trace-analysis/parse_logs.py", line 54, in __init__
    self.jobs[job_id].add_event(json_data, True)
  File "/home/spark/spark-1.3.1/trace-analysis/job.py", line 32, in add_event
    self.stages[stage_id].add_event(data, True)
  File "/home/spark/spark-1.3.1/trace-analysis/stage.py", line 292, in add_event
    task = Task(data, is_json)
  File "/home/spark/spark-1.3.1/trace-analysis/task.py", line 8, in __init__
    self.initialize_from_json(data)
  File "/home/spark/spark-1.3.1/trace-analysis/task.py", line 22, in initialize_from_json
    task_metrics = json_data["Task Metrics"]
KeyError: 'Task Metrics'

**Comment by kayousterhout** [comment]
What version of Spark are you using? Can you post the event log you're trying to parse?

**Comment by alee-altiscale** [comment]
I have encountered the same problem as well. I tried Spark `1.2.1` and `1.3.1`, both ran into the same error message.

It is reproducible when I remove the problematic entry, it looks like it always happen on the last entry that contains the `Test Metrics`. If you removed the last `SparkListenerTaskEnd`, the problem will occur on the previous one.


```
{"Event":"SparkListenerTaskEnd","Stage ID":93,"Stage Attempt ID":0,"Task Type":"ResultTask","Task End Reason":{"Reason":"Success"},"Task Info":{"Task ID":994,"Index":14,"Attempt":0,"Launch Time":1433887430627,"Executor ID":"1","Host":"103-09-04.test.com","Locality":"PROCESS_LOCAL","Speculative":false,"Getting Result Time":0,"Finish Time":1433887530380,"Failed":false,"Accumulables":[]},"Task Metrics":{"Host Name":"103-09-04.test.com","Executor Deserialize Time":3,"Executor Run Time":99584,"Result Size":44957,"JVM GC Time":5826,"Result Serialization Time":0,"Memory Bytes Spilled":0,"Disk Bytes Spilled":0,"Shuffle Read Metrics":{"Remote Blocks Fetched":38,"Local Blocks Fetched":10,"Fetch Wait Time":35776,"Remote Bytes Read":1142342077,"Local Bytes Read":300552264,"Total Records Read":48},"Input Metrics":{"Data Read Method":"Memory","Bytes Read":62197608,"Records Read":1},"Updated Blocks":[{"Block ID":"rdd_94_14","Status":{"Storage Level":{"Use Disk":false,"Use Memory":true,"Use Tachyon":false,"Deserialized":true,"Replication":1},"Memory Size":13101376,"Tachyon Size":0,"Disk Size":0}}]}}
{"Event":"SparkListenerTaskEnd","Stage ID":93,"Stage Attempt ID":0,"Task Type":"ResultTask","Task End Reason":{"Reason":"Success"},"Task Info":{"Task ID":984,"Index":6,"Attempt":0,"Launch Time":1433887430616,"Executor ID":"1","Host":"103-09-04.test.com","Locality":"PROCESS_LOCAL","Speculative":false,"Getting Result Time":0,"Finish Time":1433887534655,"Failed":false,"Accumulables":[]},"Task Metrics":{"Host Name":"103-09-04.test.com","Executor Deserialize Time":3,"Executor Run Time":103871,"Result Size":44957,"JVM GC Time":5826,"Result Serialization Time":0,"Memory Bytes Spilled":0,"Disk Bytes Spilled":0,"Shuffle Read Metrics":{"Remote Blocks Fetched":38,"Local Blocks Fetched":10,"Fetch Wait Time":27243,"Remote Bytes Read":1315089187,"Local Bytes Read":346039461,"Total Records Read":48},"Input Metrics":{"Data Read Method":"Memory","Bytes Read":68866824,"Records Read":1},"Updated Blocks":[{"Block ID":"rdd_94_6","Status":{"Storage Level":{"Use Disk":false,"Use Memory":true,"Use Tachyon":false,"Deserialized":true,"Replication":1},"Memory Size":13101376,"Tachyon Size":0,"Disk Size":0}}]}}
{"Event":"SparkListenerBlockManagerRemoved","Block Manager ID":{"Executor ID":"4","Host":"102-01-03.test.com","Port":43415},"Timestamp":1433887556658}
{"Event":"SparkListenerBlockManagerRemoved","Block Manager ID":{"Executor ID":"5","Host":"103-01-04.test.com","Port":54041},"Timestamp":1433887616658}
{"Event":"SparkListenerBlockManagerRemoved","Block Manager ID":{"Executor ID":"2","Host":"103-17-01.test.com","Port":57328},"Timestamp":1433887676659}
```

**Comment by jiadongy** [comment]
Thank You

**Comment by alee-altiscale** [comment]
The diff results look like this. 

```
diff --git a/parse_logs.py b/parse_logs.py
index e137d60..f37dc3c 100755
--- a/parse_logs.py
+++ b/parse_logs.py
@@ -34,6 +34,9 @@ class Analyzer:
       if is_json:
         json_data = get_json(line)
         event_type = json_data["Event"]
+        if json_data.get('Task Info'):
+          if json_data['Task Info']['Failed']:
+            continue
         if event_type == "SparkListenerJobStart":
           if parse_as_single_job:
             job_id = 0
```
